// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: internal/proto/event.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	RobotId       string                 `protobuf:"bytes,2,opt,name=robot_id,json=robotId,proto3" json:"robot_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Telemetry     *structpb.Struct       `protobuf:"bytes,5,opt,name=telemetry,proto3" json:"telemetry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventProto) Reset() {
	*x = EventProto{}
	mi := &file_internal_proto_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventProto) ProtoMessage() {}

func (x *EventProto) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventProto.ProtoReflect.Descriptor instead.
func (*EventProto) Descriptor() ([]byte, []int) {
	return file_internal_proto_event_proto_rawDescGZIP(), []int{0}
}

func (x *EventProto) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *EventProto) GetRobotId() string {
	if x != nil {
		return x.RobotId
	}
	return ""
}

func (x *EventProto) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *EventProto) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *EventProto) GetTelemetry() *structpb.Struct {
	if x != nil {
		return x.Telemetry
	}
	return nil
}

var File_internal_proto_event_proto protoreflect.FileDescriptor

const file_internal_proto_event_proto_rawDesc = "" +
	"\n" +
	"\x1ainternal/proto/event.proto\x12\x05proto\x1a\x1cgoogle/protobuf/struct.proto\"\xaf\x01\n" +
	"\n" +
	"EventProto\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x19\n" +
	"\brobot_id\x18\x02 \x01(\tR\arobotId\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x125\n" +
	"\ttelemetry\x18\x05 \x01(\v2\x17.google.protobuf.StructR\ttelemetryB4Z2github.com/CaueTech/celer-engine/internal/proto/pbb\x06proto3"

var (
	file_internal_proto_event_proto_rawDescOnce sync.Once
	file_internal_proto_event_proto_rawDescData []byte
)

func file_internal_proto_event_proto_rawDescGZIP() []byte {
	file_internal_proto_event_proto_rawDescOnce.Do(func() {
		file_internal_proto_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_event_proto_rawDesc), len(file_internal_proto_event_proto_rawDesc)))
	})
	return file_internal_proto_event_proto_rawDescData
}

var file_internal_proto_event_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_proto_event_proto_goTypes = []any{
	(*EventProto)(nil),      // 0: proto.EventProto
	(*structpb.Struct)(nil), // 1: google.protobuf.Struct
}
var file_internal_proto_event_proto_depIdxs = []int32{
	1, // 0: proto.EventProto.telemetry:type_name -> google.protobuf.Struct
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_proto_event_proto_init() }
func file_internal_proto_event_proto_init() {
	if File_internal_proto_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_event_proto_rawDesc), len(file_internal_proto_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_proto_event_proto_goTypes,
		DependencyIndexes: file_internal_proto_event_proto_depIdxs,
		MessageInfos:      file_internal_proto_event_proto_msgTypes,
	}.Build()
	File_internal_proto_event_proto = out.File
	file_internal_proto_event_proto_goTypes = nil
	file_internal_proto_event_proto_depIdxs = nil
}
